"use client";

/**
 * Facility booking.
 *
 * The calendar shows which days already have bookings before a date is picked,
 * so nobody taps through three screens to discover Saturday is gone. Slots are
 * generated by the server from the facility's own opening hours and slot
 * length — the client never assumes a facility opens at nine.
 *
 * A slot that has just been taken by someone else returns 409 from the unique
 * constraint, and that is surfaced as a message rather than swallowed.
 */

import { useMemo, useState } from "react";
import {
  Building2,
  CalendarCheck,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  Dumbbell,
  Info,
  Landmark,
  TriangleAlert,
  Waves,
} from "lucide-react";
import {
  Card,
  Empty,
  Notice,
  ScreenHeader,
  ScreenSkeleton,
  StaleDataNotice,
  SectionTitle,
  formatDay,
  rs,
} from "@/components/resident/ui";
import { api } from "@/lib/api";
import { useAction, useOnline, useResidentApi } from "@/lib/resident/hooks";
import type {
  Facility,
  FacilityBooking,
  FacilitySlot,
} from "@/lib/resident/types";

type Availability = {
  facility: Facility;
  month: string;
  booked_dates: Record<string, number[]>;
  selected_date: string;
  slots: FacilitySlot[];
  min_date: string;
  max_date: string;
};

const WEEKDAYS = ["M", "T", "W", "T", "F", "S", "S"];

export default function FacilitiesScreen() {
  const online = useOnline();
  const [facilityId, setFacilityId] = useState<number | null>(null);
  const [month, setMonth] = useState(() => new Date().toISOString().slice(0, 7));
  const [selected, setSelected] = useState(() => new Date().toISOString().slice(0, 10));
  const [slot, setSlot] = useState<number | null>(null);
  const [confirmed, setConfirmed] = useState<FacilityBooking | null>(null);

  const facilities = useResidentApi<{ facilities: Facility[] }>("/api/resident/facilities");
  const bookings = useResidentApi<{ bookings: FacilityBooking[] }>("/api/resident/bookings");

  const bookable = (facilities.data?.facilities ?? []).filter(
    (facility) => facility.booking_required || facility.booking_rate !== null,
  );
  const activeId = facilityId ?? bookable[0]?.id ?? null;

  const availability = useResidentApi<Availability>(
    activeId
      ? `/api/resident/facilities/${activeId}/availability?month=${month}&date=${selected}`
      : null,
  );

  const book = useAction(async () => {
    const payload = await api<{ booking: FacilityBooking }>("/api/resident/bookings", {
      method: "POST",
      body: { facility_id: activeId, booking_date: selected, slot_start: slot },
    });
    setConfirmed(payload.booking);
    setSlot(null);
    await Promise.all([availability.reload(), bookings.reload()]);
  });

  const cancel = useAction(async (bookingId: number) => {
    await api(`/api/resident/bookings/${bookingId}`, { method: "DELETE" });
    await Promise.all([availability.reload(), bookings.reload()]);
  });

  const facility = availability.data?.facility;
  const days = useMemo(() => buildMonth(month), [month]);

  return (
    <div className="r-screen r-screen--plain">
      <ScreenHeader back="/app/coop" title="Facilities" />

      {facilities.loading && !facilities.data ? <ScreenSkeleton rows={3} /> : null}
      {facilities.stale || bookings.stale || availability.stale ? <StaleDataNotice /> : null}

      {bookable.length > 0 ? (
        <div style={{ display: "flex", gap: 7, marginBottom: 14 }}>
          {bookable.map((entry) => {
            const Icon = iconFor(entry.facility_type);
            const active = entry.id === activeId;
            return (
              <button
                className={`r-btn ${active ? "r-btn--primary" : ""}`}
                key={entry.id}
                onClick={() => {
                  setFacilityId(entry.id);
                  setSlot(null);
                  setConfirmed(null);
                }}
                style={{ flex: 1, paddingInline: 10 }}
                type="button"
              >
                <Icon size={15} />
                {entry.name.split(" ")[0]}
              </button>
            );
          })}
        </div>
      ) : null}

      {facility ? (
        <Card accent>
          <div style={{ display: "flex", gap: 11, alignItems: "flex-start" }}>
            <span className="r-row__mark tint-neutral" style={{ width: 40, height: 40 }}>
              {(() => {
                const Icon = iconFor(facility.facility_type);
                return <Icon size={18} />;
              })()}
            </span>
            <div style={{ minWidth: 0 }}>
              <div style={{ fontSize: 14, fontWeight: 600 }}>{facility.name}</div>
              <div className="r-muted">{facility.detail}</div>
              <div
                className={facility.is_open ? "text-ok" : "text-mt"}
                style={{ fontSize: 11, fontWeight: 600, marginTop: 2 }}
              >
                {facility.hours_label}
                {facility.is_open === null ? "" : facility.is_open ? " · Open now" : " · Closed now"}
              </div>
            </div>
          </div>

          {facility.rules ? (
            <div style={{ marginTop: 12, paddingTop: 11, borderTop: "1px solid var(--clg)" }}>
              <div className="r-label" style={{ marginBottom: 5 }}>
                House rules
              </div>
              <p className="r-muted" style={{ lineHeight: 1.6 }}>
                {facility.rules}
              </p>
            </div>
          ) : null}

          {facility.booking_rate_label ? (
            <div className="r-muted" style={{ marginTop: 9, display: "flex", gap: 6, alignItems: "center" }}>
              <Info size={13} />
              {facility.booking_rate_label}
            </div>
          ) : null}
        </Card>
      ) : null}

      {confirmed ? (
        <Notice icon={CircleCheck} tone="ok">
          Booked — {confirmed.facility_name} on {formatDay(confirmed.booking_date)} at{" "}
          {confirmed.slot_label}.
        </Notice>
      ) : null}

      {book.error ? (
        <Notice icon={TriangleAlert} tone="er">
          {book.error}
        </Notice>
      ) : null}

      {availability.data ? (
        <Card>
          <div className="r-calendar__nav">
            <button
              aria-label="Previous month"
              className="r-iconbtn"
              onClick={() => setMonth(shiftMonth(month, -1))}
              style={{ width: 32, height: 32 }}
              type="button"
            >
              <ChevronLeft size={15} />
            </button>
            <span className="r-calendar__month">{monthLabel(month)}</span>
            <button
              aria-label="Next month"
              className="r-iconbtn"
              onClick={() => setMonth(shiftMonth(month, 1))}
              style={{ width: 32, height: 32 }}
              type="button"
            >
              <ChevronRight size={15} />
            </button>
          </div>

          <div className="r-calendar">
            {WEEKDAYS.map((day, index) => (
              <div className="r-calendar__head" key={`${day}-${index}`}>
                {day}
              </div>
            ))}
            {days.map((day, index) =>
              day === null ? (
                <span key={`lead-${index}`} />
              ) : (
                <button
                  className={[
                    "r-calendar__day",
                    availability.data!.booked_dates[day.iso] ? "has-bookings" : "",
                    day.iso === selected ? "is-selected" : "",
                  ]
                    .filter(Boolean)
                    .join(" ")}
                  disabled={day.iso < availability.data!.min_date || day.iso > availability.data!.max_date}
                  key={day.iso}
                  onClick={() => {
                    setSelected(day.iso);
                    setSlot(null);
                    setConfirmed(null);
                  }}
                  type="button"
                >
                  {day.number}
                </button>
              ),
            )}
          </div>

          <div className="r-legend">
            <span>
              <i style={{ background: "var(--cc)", border: "1px solid var(--cbr)" }} />
              Free
            </span>
            <span>
              <i style={{ background: "var(--lt-wn)" }} />
              Has bookings
            </span>
            <span>
              <i style={{ background: "var(--cr)" }} />
              Selected
            </span>
          </div>

          <div className="r-label" style={{ margin: "16px 0 7px" }}>
            Slots for {formatDay(selected)}
          </div>
          <div className="r-option-grid r-option-grid--3">
            {availability.data.slots.map((entry) => (
              <button
                className={`r-option ${slot === entry.start ? "is-selected" : ""}`}
                disabled={!entry.available}
                key={entry.start}
                onClick={() => setSlot(entry.start)}
                style={{ minHeight: 44, opacity: entry.available ? 1 : 0.45 }}
                type="button"
              >
                {entry.label}
                {entry.reason === "booked" ? (
                  <span style={{ fontSize: 9, fontWeight: 500 }}>Taken</span>
                ) : null}
              </button>
            ))}
          </div>
          {availability.data.slots.every((entry) => !entry.available) ? (
            <p className="r-muted" style={{ textAlign: "center" }}>
              Nothing free on this day. Try another date.
            </p>
          ) : null}
        </Card>
      ) : null}

      {availability.data && slot !== null ? (
        <div className="r-actionbar">
          <button
            className="r-btn r-btn--accent r-btn--block"
            disabled={book.pending || !online}
            onClick={() => void book.run()}
            type="button"
          >
            <CalendarCheck size={16} />
            {book.pending
              ? "Booking…"
              : `Confirm ${formatDay(selected)} · ${availability.data.slots.find((entry) => entry.start === slot)?.label}`}
          </button>
          {facility?.booking_rate ? (
            <div className="r-muted" style={{ marginTop: 7, textAlign: "center", fontSize: 10.5 }}>
              {rs(facility.booking_rate)} will be added to your account
            </div>
          ) : null}
        </div>
      ) : null}

      <SectionTitle>My bookings</SectionTitle>
      {bookings.data && bookings.data.bookings.length === 0 ? (
        <Empty icon={CalendarCheck} title="No bookings">
          Pick a date and a slot above to reserve a facility.
        </Empty>
      ) : null}

      {(bookings.data?.bookings ?? []).map((booking) => (
        <div className="r-list" key={booking.id} style={{ marginBottom: 8 }}>
          <div className="r-row">
            <span className="r-row__mark tint-neutral">
              <CalendarCheck size={15} />
            </span>
            <span className="r-row__body">
              <span className="r-row__title">{booking.facility_name}</span>
              <span className="r-row__sub">
                {formatDay(booking.booking_date)} · {booking.slot_label}
                {booking.amount > 0 ? ` · ${rs(booking.amount)}` : ""}
              </span>
            </span>
            <button
              className="r-btn r-btn--sm r-btn--ghost"
              disabled={cancel.pending || !online}
              onClick={() => void cancel.run(booking.id)}
              type="button"
            >
              Cancel
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}

function buildMonth(month: string) {
  const [year, monthNumber] = month.split("-").map(Number);
  const first = new Date(year, monthNumber - 1, 1);
  const total = new Date(year, monthNumber, 0).getDate();
  // getDay() is Sunday-first; this grid starts on Monday.
  const lead = (first.getDay() + 6) % 7;

  const cells: ({ iso: string; number: number } | null)[] = Array.from({ length: lead }, () => null);
  for (let day = 1; day <= total; day += 1) {
    cells.push({
      iso: `${year}-${String(monthNumber).padStart(2, "0")}-${String(day).padStart(2, "0")}`,
      number: day,
    });
  }
  return cells;
}

function shiftMonth(month: string, delta: number) {
  const [year, monthNumber] = month.split("-").map(Number);
  const next = new Date(year, monthNumber - 1 + delta, 1);
  return `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, "0")}`;
}

function monthLabel(month: string) {
  const [year, monthNumber] = month.split("-").map(Number);
  return new Intl.DateTimeFormat("en-GB", { month: "long", year: "numeric" }).format(
    new Date(year, monthNumber - 1, 1),
  );
}

function iconFor(type: Facility["facility_type"]) {
  switch (type) {
    case "pool":
      return Waves;
    case "gym":
      return Dumbbell;
    case "hall":
      return Landmark;
    default:
      return Building2;
  }
}
